### ISSUE TITLE
Cycles in method body

### ISSUE THREAD

**Issue by oliverhaase** [oliverhaase/sai#3]
In order to deal with cycles (loops), implement fixed point computation as e.g. described in https://en.wikipedia.org/wiki/Data-flow_analysis. Use a maximum number of iterations, in case the computation doesn't converge. Print an error message.

**Comment by markusheilig** [comment]
implemented in https://github.com/oliverhaase/sai/blob/master/src/sai/ea/SummaryInformation.scala
